name = "aired"
main = "src/index.ts"
compatibility_date = "2025-04-01"
workers_dev = true

[assets]
directory = "../web"

[[r2_buckets]]
binding = "PAGES_BUCKET"
bucket_name = "aired-pages"

[[kv_namespaces]]
binding = "PAGES_KV"
id = "6388d6b3b6c04fe5ad8529ae029e723e"

# Custom domain
[[routes]]
pattern = "aired.sh/*"
zone_name = "aired.sh"

[[routes]]
pattern = "aired.sh"
zone_name = "aired.sh"
