import pc from 'picocolors'
import { VERSION, CLI_NAME } from './constants.js'
import { getSession } from '../core/session.js'
import type { GlobalOpts } from './config.js'

// ASCII art generated by: npx figlet-cli -f "ANSI Shadow" "aired"
const ART = `
 █████╗ ██╗██████╗ ███████╗██████╗
██╔══██╗██║██╔══██╗██╔════╝██╔══██╗
███████║██║██████╔╝█████╗  ██║  ██║
██╔══██║██║██╔══██╗██╔══╝  ██║  ██║
██║  ██║██║██║  ██║███████╗██████╔╝
╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚══════╝╚═════╝
`.trimStart()

export function banner(opts?: GlobalOpts): string {
  const colored = ART.split('\n').map(line => pc.bold(line)).join('\n')
  const info = pc.dim(`${CLI_NAME} v${VERSION}`)

  const isQuiet = opts?.quiet === true || opts?.json === true
  const session = isQuiet ? null : getSession()
  const sessionLine = session !== null ? `\n${pc.dim(`signed in as @${session.user.login}`)}` : ''

  return `${colored}${info}${sessionLine}\n`
}
